name: Update Assets

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9.x]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install -r scripts/requirements.txt
      shell: bash
    - run: python scripts/update_assets.py
      name: Update assets
      env:
        - name: PYTHON_VERSION
          value: ${{ matrix.python-version }}
      shell: bash
    
    - run : git config user.name github-actions
      shell: bash
    - run : git config user.email github-actions@github.com
      shell: bash
    - run : git add -A
      shell: bash
    - run : git commit -m "Updating Assets by github-actions"
      shell: bash
    - run : git push origin HEAD:main --force
      shell: bash
    